[package]
name = "async-ops"
version = "0.1.0"
authors = ["Sanjin Sehic <saserr@gmail.com>"]
edition = "2021"

[dependencies]
futures = "0.3"
paste = "1.0"
pin-project-lite = "0.2"

[dev-dependencies]
doc-comment = "0.3"
